logging:
  level:
    eu.nebulouscloud.exn: TRACE

spring:
  profiles: default
  main:
    web-application-type: none
  jms:
    pub-sub-domain: true

application:
  exn:
    config:
      url: '${ACTIVEMQ_HOST:nebulous-activemq}'
      port: '${ACTIVEMQ_PORT:5672}'
      username: 'admin'
      password: 'admin'
      connectTimeout: 20 #min
      readTimeout: 20 #min
  sal:
    protocol: 'http'
    host: '${SAL_HOST:nebulous-sal}'
    port: '${SAL_PORT:8080}'
    api: 'sal'
    username: '${SAL_USER}'
    password: '${SAL_PASSWORD}'
  jms:
    topic: 'eu.nebulouscloud'