- project:
    check:
      jobs:
        - opendev-buildset-registry
        - nebulous-exn-middleware-helm-lint
        - nebulous-exn-middleware-build-container-images
        - nebulous-exn-middleware-hadolint
        - nebulous-platform-apply-helm-charts
        - nox-linters
    gate:
      jobs:
        - opendev-buildset-registry
        - nebulous-exn-middleware-helm-lint
        - nebulous-exn-middleware-upload-container-images
        - nebulous-exn-middleware-hadolint
        - nebulous-platform-apply-helm-charts
        - nox-linters
    promote:
      jobs:
        - nebulous-exn-middleware-promote-container-images
